version: "3.8"
services:
  bookstore-api:
    build: ../backend
    volumes:
      - ../backend:/app
    ports:
      - "7721:5000"
  bookstore-app:
    build: ../frontend
    volumes:
      - ../frontend:/app
    ports:
      - "7720:3000"
