version: "3.8"
services:
  bookstore-api:
    build:
      context: ../backend
      target: development
    volumes:
      - ../backend:/app
    ports:
      - "7721:5000"
    environment:
      - FLASK_ENV=development

  bookstore-app:
    build:
      context: ../frontend
      target: development
    volumes:
      - ../frontend:/app
    ports:
      - "7720:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:7721

